const fs = require('fs')

const inputStrings = [
  '/programs/rick-steves-special-the-story-of-fascism-in-europe-70789',
'/programs/tastemakers-70787',
'/programs/hitler-s-mein-kampf-prelude-to-the-holocaust-70932',
'/programs/expeditions-with-patrick-mcmillan-70514',
'/programs/people-of-the-north-71003',
'/programs/laura-flanders-friends-71047',
'/programs/earthrise-the-first-lunar-voyage-70551',
'/programs/global-reef-expedition-70717',
'/programs/rick-steves-egypt-yesterday-today-70884',
'/programs/great-white-shark-70901',
'/programs/me-dorothy-and-this-road-to-oz-70810',
'/programs/women-outward-bound-70766',
'/programs/grandpa-s-war-story-goes-viral-70912',
'/programs/lifeline-pearl-harbor-s-unknown-hero-70797',
'/programs/china-frame-by-frame-71006',
'/programs/bears-of-durango-70886',
'/programs/rick-steves-europe-a-symphonic-journey-70906',
'/programs/the-kennedy-half-century-70535',
'/programs/bridging-divides-sharing-heartbeats-71016',
'/programs/welcome-to-my-farm-70941',
'/programs/right-footed-70666',
'/programs/georgia-o-keeffe-the-brightness-of-light-71039',
'/programs/america-the-bountiful-71017',
'/programs/outside-beyond-the-lens-70826',
'/programs/rick-steves-best-of-the-alps-70987',
'/programs/doug-s-geology-journal-70952',
'/programs/discover-beethoven-s-fifth-70529',
'/programs/eliades-ochoa-live-at-la-casa-de-la-trova-70926',
'/programs/cyberwork-and-the-american-dream-70808',
'/programs/real-road-adventures-with-jeff-wilson-70956',
'/programs/the-inn-at-little-washington-a-delicious-documentary-70902',
'/programs/america-s-secret-war-70764',
'/programs/playing-frisbee-in-north-korea-70879',
'/programs/journey-home-to-the-uss-arizona-70771',
'/programs/conscious-living-70922',
'/programs/betrayed-surviving-an-american-concentration-camp-70945',
'/programs/wine-first-71004',
'/programs/keeping-score-70341',
'/programs/osiris-rex-countdown-to-launch-70768',
'/programs/after-auschwitz-70835',
'/programs/village-of-death-oradour-sur-glane-1944-71013',
'/programs/paleo-sleuths-70703',
'/programs/rick-steves-luther-and-the-reformation-70705',
'/programs/rick-steves-europe-70378',
'/programs/peleliu-wwii-s-most-well-preserved-battlefield-71037',
'/programs/dad-s-secret-war-france-1944-71036',
'/programs/a-ripple-of-hope-70395',
'/programs/the-piping-plovers-of-moonlight-bay-71038',
'/programs/urban-conversion-70601',
'/programs/art-wolfe-s-travels-to-the-edge-amazing-encounters-70432',
'/programs/jack-taylor-the-enterprise-70968',
'/programs/angle-of-attack-70474',
'/programs/rick-steves-iceland-71027',
'/programs/flying-the-feathered-edge-the-bob-hoover-project-70927',
'/programs/world-peace-and-other-4th-grade-achievements-70427',
'/programs/remembering-leonard-nimoy-70742',
'/programs/dream-of-italy-travel-transform-and-thrive-70957',
'/programs/4-wheel-bob-70757',
'/programs/lucky-chow-70617',
'/programs/art-wolfe-s-travels-to-the-edge-70358',
'/programs/the-cure-for-hate-bearing-witness-to-auschwitz-71041',
'/programs/surrender-on-the-uss-missouri-70905',
'/programs/the-world-war-ii-foundation-collection-70531',
'/programs/the-reagan-presidency-70508',
'/programs/survivors-of-malmedy-december-1944-70770',
'/programs/project-asteroid-mapping-bennu-70767',
'/programs/let-there-be-light-70731',
'/programs/unsung-heroes-the-story-of-america-s-female-patriots-70753',
'/programs/the-misty-experiment-the-secret-battle-for-the-ho-chi-minh-trail-70958',
'/programs/bob-ross-the-happy-painter-70861',
'/programs/rick-steves-hunger-and-hope-70883',
'/programs/a-final-landing-on-iwo-jima-71020',
'/programs/coronation-girls-71040',
'/programs/rick-steves-special-cruising-the-mediterranean-70903',
'/programs/dear-albania-70609',
'/programs/dream-of-europe-71042',
'/programs/new-scandinavian-cooking-70422',
'/programs/islands-without-cars-70948',
'/programs/trauma-healers-70915',
'/programs/perfect-36-when-women-won-the-vote-70736',
'/programs/we-hold-these-truths-the-global-quest-for-liberty-70989',
'/programs/higgins-ridge-71015',
'/programs/rick-steves-special-andaluc-a-the-best-of-southern-spain-70769',
'/programs/broadside-70400',
'/programs/bob-ross-experience-the-70940',
'/programs/christina-cooks-back-to-the-cutting-board-71026',
'/programs/since-the-bombing-of-pan-am-flight-103-70700',
'/programs/fannie-s-last-supper-70434',
'/programs/golden-eagles-witnesses-to-a-changing-west-71000',
'/programs/yoga-in-practice-70867',
'/programs/dismantling-democracy-70881',
'/programs/summer-help-the-70750',
'/programs/happy-holidays-with-the-boston-pops-70691',
'/programs/true-north-the-sean-swarner-story-70749',
'/programs/crossing-the-70925',
'/programs/sex-lies-and-the-priesthood-70933',
'/programs/desert-dreams-70777',
'/programs/elmore-leonard-but-don-t-try-to-write-70951',
'/programs/swimming-in-auschwitz-70398',
'/programs/eva-a-7063-70794',
'/programs/10-that-changed-america-70687',
'/programs/ellie-s-real-good-food-70727',
'/programs/the-himalaya-connection-70748',
'/programs/omaha-beach-honor-and-sacrifice-70602',
'/programs/america-s-heartland-70356',
'/programs/jayhawkers-70831',
'/programs/parkland-healing-a-community-and-a-nation-70847',
'/programs/beauty-on-the-wing-life-story-of-the-monarch-butterfly-70874',
'/programs/start-up-food-and-beverage-70995',
'/programs/civil-war-the-untold-story-70532',
'/programs/black-ballerina-70677',
'/programs/behind-the-wings-shorts-71044',
'/programs/j-schwanke-s-life-in-bloom-70934',
'/programs/1st-to-fight-pacific-war-marines-70878',
'/programs/the-tuskegee-airmen-return-to-ramitelli-70984',
'/programs/start-up-70547',
'/programs/west-of-the-west-tales-from-california-s-channel-islands-70718',
'/programs/changing-seas-70428',
'/programs/the-highpointers-with-the-bargo-brothers-70988',
'/programs/not-a-real-show-0',
'/programs/nazi-law-legally-blind-70694',
'/programs/modern-pioneering-with-georgia-pellegrini-70873',
'/programs/landslide-the-presidency-of-herbert-hoover-70944',
'/programs/d-day-at-pointe-du-hoc-70818',
'/programs/versailles-73-american-runway-revolution-70698',
'/programs/rick-steves-special-european-festivals-70752',
'/programs/silent-sacrifice-stories-of-japanese-american-incarceration-70772',
'/programs/stories-of-survival-70939',
'/programs/rick-steves-art-of-europe-70982',
'/programs/elvis-and-the-uss-arizona-70923',
'/programs/dream-of-italy-70623',
'/programs/jazzy-vegetarian-70607',
'/programs/rick-steves-art-bites-71029',
'/programs/smart-travels-pacific-rim-with-rudy-maxa-70229',
'/programs/rick-steves-special-european-easter-70649',
'/programs/cuba-the-forgotten-revolution-70611',
'/programs/inside-high-noon-70965',
'/programs/ocean-invaders-70998',
'/programs/rommel-the-soldier-the-son-and-hitler-70904',
'/programs/portraits-in-architecture-70792',
'/programs/frank-ferrante-s-groucho-70943',
'/programs/america-s-socialist-experiment-70855',
'/programs/rise-of-the-freemen-71014',
'/programs/an-ocean-mystery-the-missing-catch-70713',
'/programs/treblinka-s-last-witness-70681',
'/programs/the-seabees-on-iwo-jima-70983',
'/programs/a-craftsman-s-legacy-70563',
'/programs/triumph-of-the-nerds-70785',
'/programs/rick-steves-special-european-christmas-70407',
'/programs/the-u-boat-and-the-rocket-71002',
'/programs/pathways-to-invention-71018',
'/programs/for-love-of-liberty-the-story-of-america-s-black-patriots-70403',
'/programs/frozen-obsession-70893',
'/programs/art-basel-a-portrait-70597',
'/programs/love-wins-over-hate-70875',
'/programs/beneath-the-polar-sun-71019',
'/programs/most-valuable-players-70488',
'/programs/confluence-71021',
'/programs/road-to-the-globe-troilus-cressida-70625',
'/programs/orchestrating-change-70964',
'/programs/d-day-over-normandy-70735',
'/programs/rick-steves-experiencing-europe-71030',
'/programs/invisible-threads-from-wireless-to-war-70962',
'/programs/the-new-fire-70793',
'/programs/merrill-s-marauders-they-volunteered-for-this-70961',
'/programs/unsettled-history-70942',
'/programs/the-portillo-expeditition-mystery-on-bougainville-island-70900',
'/programs/hacking-your-mind-70852',
'/programs/olympic-pride-american-prejudice-71022',
'/programs/the-wild-ponies-of-chincoteague-70817',
'/programs/discover-the-firebird-70877',
'/programs/kasturba-gandhi-accidental-activist-70981',
'/programs/glacier-park-s-night-of-the-grizzlies-70435',
'/programs/curious-traveler-70575',
'/programs/searching-our-quest-for-meaning-in-the-age-of-science-70959',
'/programs/behind-the-wings-70849',
'/programs/the-joy-of-painting-with-bob-ross-70605',
'/programs/code-name-ayalon-70999',
'/programs/smart-travels-europe-with-rudy-maxa-70013',
'/programs/to-the-ends-of-the-earth-70783',
'/programs/family-travel-with-colleen-kelly-70554',
'/programs/growing-a-greener-world-70473',
'/programs/shanghai-1937-where-world-war-ii-began-70781',
'/programs/secrets-of-sacred-architecture-70931',
'/programs/chavis-chronicles-the-70924',
'/programs/my-greek-table-with-diane-kochilas-70743',
'/programs/saving-sea-turtles-preventing-extinction-70724',
'/programs/fixed-the-science-fiction-of-human-enhancement-70573',
'/programs/fall-in-love-with-music-70686',
'/programs/anahita-a-mother-s-journey-70976',
'/programs/eliades-ochoa-from-cuba-to-the-world-70908',
'/programs/discover-vivaldi-s-four-seasons-70518',
'/programs/day-of-days-june-6-1944-70550',
'/programs/the-burren-heart-of-stone-70979',
'/programs/last-artifact-the-70868',
'/programs/finding-traction-70578',
'/programs/her-war-her-story-world-war-ii-70960'
]

const generateObjects = (strings) => {
  return strings.reduce((acc, str) => {
    const match = str.match(/(.*?)-(\d{5})$/)

    if (match) {
      const basePath = match[1] // Extract the part before the 5-digit number
      const digits = match[2] // Extract the 5-digit number
      const transformedValue = `${basePath}/${digits}/${basePath.split('/').pop().replace(/-?\d+$/, '').replace(/-$/, '')}`
      acc[str] = transformedValue
    } else {
      console.warn(`No match for string: ${str}`)
    }

    return acc
  }, {})
}

const result = generateObjects(inputStrings)

fs.writeFile('output.json', JSON.stringify(result, null, 2), (err) => {
  if (err) {
    console.error('Error writing to file:', err)
  } else {
    console.info('File successfully written to output.json')
  }
})


